name: Angular compile and load artifact

on:
  workflow_call:
    inputs:
      baseHref:
        description: 'Base Href'
        type: string
        required: true
        default: '/'
      nodeVersion:
        description: 'Node Version'
        type: string
        required: true
        default: '18.x'
      folder:
        description: 'Folder of project'
        type: string
        required: true
        default: '.'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.nodeVersion }}

      - name: Set directory
        if: ${{ inputs.folder }} != '.'
        run: cd ${{ inputs.folder }}

      - name: Install Dependencies
        run: yarn install --force

      #compilando el proyecto
      - name: Build Angular App
        run: |
          yarn run build --configuration=production --base-href=/${{ inputs.baseHref }}/
          
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist
